# Generated by Django 3.2.12 on 2022-04-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='constituency',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='name',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='symbol',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
